### ISSUE TITLE
Needs a 64x64 and 128x128 icon

### ISSUE THREAD

**Issue by nedrichards** [flathub/io.github.Freedoom-Phase-1#1]
In order to show up on the [apps page](https://beta.flathub.org/apps) this needs at least a 64x64 icon. The icon this app ships isn't a real app icon, should we try and commission something and contribute it upstream?

**Comment by Alexander-Wilms** [comment]
I think that'd be a good solution. But how would we commission an icon?

**Comment by nedrichards** [comment]
Talk to some designers!

**Comment by Alexander-Wilms** [comment]
An [issue](https://github.com/freedoom/freedoom/issues/123) has already been created upstream.

**Comment by Alexander-Wilms** [comment]
Fixed for now.
