### ISSUE TITLE
Build failed on arm/aarch64

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/io.github.Freedoom-Phase-1#9]
It seems that the last version of GZDoom [failed to build](https://flathub.org/builds/#/builders/2/builds/7405) on arm and aarch64 for some reason.

**Comment by AsciiWolf** [comment]
Failed on Freedoom-Phase-1 and FreeDM as well.

**Comment by AsciiWolf** [comment]
Build failed [again](https://flathub.org/builds/#/builders/2/builds/7585).

**Comment by Alexander-Wilms** [comment]
Yeah, I just noticed that the CI icon in the commit history indicates to status of the repo-test buildbot, Not the regular one, which builds the project on all platforms. asmjit seems to simply not support ARM, and I haven't found the reason for the immintrin.h error, so I'll disable these builds for now.

**Comment by Alexander-Wilms** [comment]
Fixed in https://github.com/flathub/io.github.Freedoom-Phase-1/commit/9f916ec6987c150e787cfe5967ea6a8ad1278515
